# Homework 3 Setup

In [5]:
# Download and decompress data into your Jupyter environment

import urllib.request
import io
import gzip


for file in ['web-NotreDame.txt']:
    print ('Downloading compressed image of', file)
    source = urllib.request.urlopen("https://snap.stanford.edu/data/" + file + ".gz")
    compressedFile = io.BytesIO(source.read())
    decompressedFile = gzip.GzipFile(fileobj=compressedFile)

    with open(file, 'wb') as outfile:
        outfile.write(decompressedFile.read())
        outfile.close()
        print ('Saved', file)

        
        
#https://snap.stanford.edu/data/web-NotreDame.txt.gz

Downloading compressed image of web-NotreDame.txt
Saved web-NotreDame.txt

## Step 3.2

In [2]:
import csv
import pandas as pd
import numpy as np
import re

In [3]:
# Execute this once, the first time you run
!pip install networkx

# Disable Python warning messages - you should probably only run this before submission

import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: networkx in /opt/conda/lib/python3.6/site-packages
Requirement already satisfied: decorator>=4.1.0 in /opt/conda/lib/python3.6/site-packages (from networkx)

In [103]:

NotreDame_df = pd.read_csv('web-NotreDame.txt', header=[0,1,2,3], delimiter="\t").reset_index()
NotreDame_df.columns = ["from_node", "to_node"]
NotreDame_df = NotreDame_df[(NotreDame_df['from_node'] < 10000)]
NotreDame_df = NotreDame_df[(NotreDame_df['to_node'] < 10000)]


NotreDame_df

       from_node  to_node
0              0        0
1              0        1
2              0        2
3              0        3
4              0        4
5              0        5
6              0        6
7              0        7
8              0        8
9              0        9
10             0       10
11             0       11
12             0       12
13             0       13
14             0       14
15             0       15
16             0       16
17             1        0
18             1        7
19             1       17
20             1       18
21             1       19
22             1       20
23             1       21
24             1       22
25             1       23
26             1       24
27             1       25
28             1       26
29             1       27
...          ...      ...
63264       9960        0
63265       9960     1273
63266       9960     9960
63273       9961        0
63274       9961     1273
63275       9961     9961
63360       9964       45
63361       9964     3731
63362       9964     6275
63363       9964     9964
63370       9965     6275
63393       9967        0
63394       9967     3950
63395       9967     5242
63396       9967     9967
63417       9968        0
63418       9968     3950
63419       9968     5242
63420       9968     9968
63432       9970     9971
63441       9972     5526
63466       9977     2742
63467       9977     6596
63476       9978     6596
63486       9980     2742
63487       9980     6596
63544       9981     2742
63545       9981     6596
63634       9990     9995
63636       9995     9990

[37841 rows x 2 columns]

In [44]:
def divide(x):
    return float(1/x)

In [104]:
helper1 = NotreDame_df.groupby('from_node').count().reset_index()
helper1.columns = ["from_node", "count"]

helper1['count'] = helper1['count'].apply(divide)
helper1.columns = ["from_node", "weight"]

helper1

      from_node    weight
0             0  0.058824
1             1  0.040000
2             3  0.166667
3             4  0.023256
4             5  0.142857
5             6  0.025000
6             7  0.025000
7             8  0.083333
8             9  0.058824
9            10  0.012987
10           11  0.018182
11           12  0.500000
12           13  0.500000
13           14  1.000000
14           15  0.076923
15           16  0.090909
16           17  0.100000
17           18  0.333333
18           19  0.010638
19           20  0.004149
20           21  0.083333
21           22  0.500000
22           23  0.071429
23           24  0.071429
24           25  0.038462
25           26  0.090909
26           27  0.076923
27           28  1.000000
28           29  0.062500
29           30  0.200000
...         ...       ...
5863       9922  1.000000
5864       9923  1.000000
5865       9924  0.500000
5866       9927  1.000000
5867       9928  0.500000
5868       9929  0.500000
5869       9936  1.000000
5870       9937  1.000000
5871       9941  1.000000
5872       9942  1.000000
5873       9945  0.500000
5874       9946  0.333333
5875       9950  0.500000
5876       9951  1.000000
5877       9955  0.500000
5878       9957  0.333333
5879       9960  0.333333
5880       9961  0.333333
5881       9964  0.250000
5882       9965  1.000000
5883       9967  0.250000
5884       9968  0.250000
5885       9970  1.000000
5886       9972  1.000000
5887       9977  0.500000
5888       9978  1.000000
5889       9980  0.500000
5890       9981  0.500000
5891       9990  1.000000
5892       9995  1.000000

[5893 rows x 2 columns]

In [105]:
helper2 = NotreDame_df.merge(helper1, left_on=['from_node'], right_on=['from_node']).dropna()
helper2

       from_node  to_node    weight
0              0        0  0.058824
1              0        1  0.058824
2              0        2  0.058824
3              0        3  0.058824
4              0        4  0.058824
5              0        5  0.058824
6              0        6  0.058824
7              0        7  0.058824
8              0        8  0.058824
9              0        9  0.058824
10             0       10  0.058824
11             0       11  0.058824
12             0       12  0.058824
13             0       13  0.058824
14             0       14  0.058824
15             0       15  0.058824
16             0       16  0.058824
17             1        0  0.040000
18             1        7  0.040000
19             1       17  0.040000
20             1       18  0.040000
21             1       19  0.040000
22             1       20  0.040000
23             1       21  0.040000
24             1       22  0.040000
25             1       23  0.040000
26             1       24  0.040000
27             1       25  0.040000
28             1       26  0.040000
29             1       27  0.040000
...          ...      ...       ...
37811       9960        0  0.333333
37812       9960     1273  0.333333
37813       9960     9960  0.333333
37814       9961        0  0.333333
37815       9961     1273  0.333333
37816       9961     9961  0.333333
37817       9964       45  0.250000
37818       9964     3731  0.250000
37819       9964     6275  0.250000
37820       9964     9964  0.250000
37821       9965     6275  1.000000
37822       9967        0  0.250000
37823       9967     3950  0.250000
37824       9967     5242  0.250000
37825       9967     9967  0.250000
37826       9968        0  0.250000
37827       9968     3950  0.250000
37828       9968     5242  0.250000
37829       9968     9968  0.250000
37830       9970     9971  1.000000
37831       9972     5526  1.000000
37832       9977     2742  0.500000
37833       9977     6596  0.500000
37834       9978     6596  1.000000
37835       9980     2742  0.500000
37836       9980     6596  0.500000
37837       9981     2742  0.500000
37838       9981     6596  0.500000
37839       9990     9995  1.000000
37840       9995     9990  1.000000

[37841 rows x 3 columns]

In [140]:
M = np.zeros((10000,10000))

In [141]:
def updateM(row):
    #print(row.iloc[2])
    M[int(row.iloc[1])][int(row.iloc[0])] = row.iloc[2]

In [142]:
#helper2.iloc[0,2]
#helper2.apply(updateM, axis=1)
#helper2.apply(lambda x: updateM(x['weight'], x['from_node'], x['to_node']), axis=1)
#helper2.apply(, axis=1)
some = helper2.apply(lambda x: updateM(x),axis=1)

In [148]:
M

array([[ 0.05882353,  0.04      ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.05882353,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.05882353,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

## Step 3.3

In [149]:
def pagerank(M, alpha, num_iter):
    m = len(M)
    beta = 1 - alpha
    rank = np.ones(m)
    
    for i in range(num_iter):
        new_rank = alpha*(np.dot(M,rank))+beta
        rank  = new_rank
    return rank

In [150]:
M[10:30,10:30]

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.01298701,  0.01818182,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.01298701,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.01298701,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.        ,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.        ,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.        ,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.08333333,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.        ,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.        ,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.        ,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.        ,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.0106383 ,
         0.00414938,  0.        ,  0.        ,  0.07142857,  0.07142857,
         0.03846154,  0.09090909,  0.07692308,  0.        ,  0.        ]])

In [170]:
result = pagerank(M, 0.85, 15)

#Output a DataFrame with the schema (id, pagerank)
#containing the original IDs and PageRanks of the 10 nodes with highest PageRank, in descending order.

pagerank_df = pd.DataFrame(result)


pagerank_df = pagerank_df.sort_values(by=0, ascending=False)
pagerank_df = pagerank_df.reset_index()
pagerank_df.columns = ["id", "pagerank"]

pagerank_df[:10]

     id    pagerank
0     0  224.702638
1  1973  189.250314
2  1790   53.438593
3  1828   50.954873
4     1   27.975911
5   238   26.779136
6   140   23.520898
7    14   22.232264
8    16   21.591054
9   162   18.283386